// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: muster/muster.proto

package muster

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MusterRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *MusterRequest) Reset() {
	*x = MusterRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_muster_muster_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MusterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MusterRequest) ProtoMessage() {}

func (x *MusterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_muster_muster_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MusterRequest.ProtoReflect.Descriptor instead.
func (*MusterRequest) Descriptor() ([]byte, []int) {
	return file_muster_muster_proto_rawDescGZIP(), []int{0}
}

func (x *MusterRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type MusterReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ip     string `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Ncores uint32 `protobuf:"varint,2,opt,name=ncores,proto3" json:"ncores,omitempty"`
}

func (x *MusterReply) Reset() {
	*x = MusterReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_muster_muster_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MusterReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MusterReply) ProtoMessage() {}

func (x *MusterReply) ProtoReflect() protoreflect.Message {
	mi := &file_muster_muster_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MusterReply.ProtoReflect.Descriptor instead.
func (*MusterReply) Descriptor() ([]byte, []int) {
	return file_muster_muster_proto_rawDescGZIP(), []int{1}
}

func (x *MusterReply) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *MusterReply) GetNcores() uint32 {
	if x != nil {
		return x.Ncores
	}
	return 0
}

type LogsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LogsMapPtr uint64 `protobuf:"varint,1,opt,name=logs_map_ptr,json=logsMapPtr,proto3" json:"logs_map_ptr,omitempty"`
}

func (x *LogsRequest) Reset() {
	*x = LogsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_muster_muster_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogsRequest) ProtoMessage() {}

func (x *LogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_muster_muster_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogsRequest.ProtoReflect.Descriptor instead.
func (*LogsRequest) Descriptor() ([]byte, []int) {
	return file_muster_muster_proto_rawDescGZIP(), []int{2}
}

func (x *LogsRequest) GetLogsMapPtr() uint64 {
	if x != nil {
		return x.LogsMapPtr
	}
	return 0
}

type LogsReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LogsMapPtr uint64 `protobuf:"varint,1,opt,name=logs_map_ptr,json=logsMapPtr,proto3" json:"logs_map_ptr,omitempty"`
}

func (x *LogsReply) Reset() {
	*x = LogsReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_muster_muster_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LogsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogsReply) ProtoMessage() {}

func (x *LogsReply) ProtoReflect() protoreflect.Message {
	mi := &file_muster_muster_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogsReply.ProtoReflect.Descriptor instead.
func (*LogsReply) Descriptor() ([]byte, []int) {
	return file_muster_muster_proto_rawDescGZIP(), []int{3}
}

func (x *LogsReply) GetLogsMapPtr() uint64 {
	if x != nil {
		return x.LogsMapPtr
	}
	return 0
}

var File_muster_muster_proto protoreflect.FileDescriptor

var file_muster_muster_proto_rawDesc = []byte{
	0x0a, 0x13, 0x6d, 0x75, 0x73, 0x74, 0x65, 0x72, 0x2f, 0x6d, 0x75, 0x73, 0x74, 0x65, 0x72, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x6d, 0x75, 0x73, 0x74, 0x65, 0x72, 0x22, 0x1f, 0x0a,
	0x0d, 0x4d, 0x75, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x35,
	0x0a, 0x0b, 0x4d, 0x75, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x70, 0x12, 0x16, 0x0a,
	0x06, 0x6e, 0x63, 0x6f, 0x72, 0x65, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x6e,
	0x63, 0x6f, 0x72, 0x65, 0x73, 0x22, 0x2f, 0x0a, 0x0b, 0x4c, 0x6f, 0x67, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x20, 0x0a, 0x0c, 0x6c, 0x6f, 0x67, 0x73, 0x5f, 0x6d, 0x61, 0x70,
	0x5f, 0x70, 0x74, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0a, 0x6c, 0x6f, 0x67, 0x73,
	0x4d, 0x61, 0x70, 0x50, 0x74, 0x72, 0x22, 0x2d, 0x0a, 0x09, 0x4c, 0x6f, 0x67, 0x73, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x12, 0x20, 0x0a, 0x0c, 0x6c, 0x6f, 0x67, 0x73, 0x5f, 0x6d, 0x61, 0x70, 0x5f,
	0x70, 0x74, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0a, 0x6c, 0x6f, 0x67, 0x73, 0x4d,
	0x61, 0x70, 0x50, 0x74, 0x72, 0x32, 0x7c, 0x0a, 0x09, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72,
	0x61, 0x72, 0x12, 0x38, 0x0a, 0x08, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x12, 0x15,
	0x2e, 0x6d, 0x75, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x4d, 0x75, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x6d, 0x75, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x4d,
	0x75, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x35, 0x0a, 0x09,
	0x53, 0x65, 0x74, 0x75, 0x70, 0x4c, 0x6f, 0x67, 0x73, 0x12, 0x13, 0x2e, 0x6d, 0x75, 0x73, 0x74,
	0x65, 0x72, 0x2e, 0x4c, 0x6f, 0x67, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x11,
	0x2e, 0x6d, 0x75, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x4c, 0x6f, 0x67, 0x73, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x22, 0x00, 0x42, 0x1a, 0x5a, 0x18, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x61, 0x77, 0x61, 0x64, 0x79, 0x6e, 0x2f, 0x6d, 0x75, 0x73, 0x74, 0x65, 0x72, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_muster_muster_proto_rawDescOnce sync.Once
	file_muster_muster_proto_rawDescData = file_muster_muster_proto_rawDesc
)

func file_muster_muster_proto_rawDescGZIP() []byte {
	file_muster_muster_proto_rawDescOnce.Do(func() {
		file_muster_muster_proto_rawDescData = protoimpl.X.CompressGZIP(file_muster_muster_proto_rawDescData)
	})
	return file_muster_muster_proto_rawDescData
}

var file_muster_muster_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_muster_muster_proto_goTypes = []interface{}{
	(*MusterRequest)(nil), // 0: muster.MusterRequest
	(*MusterReply)(nil),   // 1: muster.MusterReply
	(*LogsRequest)(nil),   // 2: muster.LogsRequest
	(*LogsReply)(nil),     // 3: muster.LogsReply
}
var file_muster_muster_proto_depIdxs = []int32{
	0, // 0: muster.Registrar.Register:input_type -> muster.MusterRequest
	2, // 1: muster.Registrar.SetupLogs:input_type -> muster.LogsRequest
	1, // 2: muster.Registrar.Register:output_type -> muster.MusterReply
	3, // 3: muster.Registrar.SetupLogs:output_type -> muster.LogsReply
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_muster_muster_proto_init() }
func file_muster_muster_proto_init() {
	if File_muster_muster_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_muster_muster_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MusterRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_muster_muster_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MusterReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_muster_muster_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LogsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_muster_muster_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LogsReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_muster_muster_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_muster_muster_proto_goTypes,
		DependencyIndexes: file_muster_muster_proto_depIdxs,
		MessageInfos:      file_muster_muster_proto_msgTypes,
	}.Build()
	File_muster_muster_proto = out.File
	file_muster_muster_proto_rawDesc = nil
	file_muster_muster_proto_goTypes = nil
	file_muster_muster_proto_depIdxs = nil
}
