// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.4
// 	protoc        v3.12.4
// source: shep_optimizer/shep_optimizer.proto

package shep_remote_muster

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ControlEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Knob          string                 `protobuf:"bytes,1,opt,name=knob,proto3" json:"knob,omitempty"`
	Val           uint64                 `protobuf:"varint,2,opt,name=val,proto3" json:"val,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControlEntry) Reset() {
	*x = ControlEntry{}
	mi := &file_shep_optimizer_shep_optimizer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlEntry) ProtoMessage() {}

func (x *ControlEntry) ProtoReflect() protoreflect.Message {
	mi := &file_shep_optimizer_shep_optimizer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlEntry.ProtoReflect.Descriptor instead.
func (*ControlEntry) Descriptor() ([]byte, []int) {
	return file_shep_optimizer_shep_optimizer_proto_rawDescGZIP(), []int{0}
}

func (x *ControlEntry) GetKnob() string {
	if x != nil {
		return x.Knob
	}
	return ""
}

func (x *ControlEntry) GetVal() uint64 {
	if x != nil {
		return x.Val
	}
	return 0
}

type RewardEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Val           float32                `protobuf:"fixed32,2,opt,name=val,proto3" json:"val,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RewardEntry) Reset() {
	*x = RewardEntry{}
	mi := &file_shep_optimizer_shep_optimizer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RewardEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RewardEntry) ProtoMessage() {}

func (x *RewardEntry) ProtoReflect() protoreflect.Message {
	mi := &file_shep_optimizer_shep_optimizer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RewardEntry.ProtoReflect.Descriptor instead.
func (*RewardEntry) Descriptor() ([]byte, []int) {
	return file_shep_optimizer_shep_optimizer_proto_rawDescGZIP(), []int{1}
}

func (x *RewardEntry) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RewardEntry) GetVal() float32 {
	if x != nil {
		return x.Val
	}
	return 0
}

type StartOptimizerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NTrials       uint32                 `protobuf:"varint,1,opt,name=n_trials,json=nTrials,proto3" json:"n_trials,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartOptimizerRequest) Reset() {
	*x = StartOptimizerRequest{}
	mi := &file_shep_optimizer_shep_optimizer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartOptimizerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartOptimizerRequest) ProtoMessage() {}

func (x *StartOptimizerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shep_optimizer_shep_optimizer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartOptimizerRequest.ProtoReflect.Descriptor instead.
func (*StartOptimizerRequest) Descriptor() ([]byte, []int) {
	return file_shep_optimizer_shep_optimizer_proto_rawDescGZIP(), []int{2}
}

func (x *StartOptimizerRequest) GetNTrials() uint32 {
	if x != nil {
		return x.NTrials
	}
	return 0
}

type StartOptimizerReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Done          bool                   `protobuf:"varint,1,opt,name=done,proto3" json:"done,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartOptimizerReply) Reset() {
	*x = StartOptimizerReply{}
	mi := &file_shep_optimizer_shep_optimizer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartOptimizerReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartOptimizerReply) ProtoMessage() {}

func (x *StartOptimizerReply) ProtoReflect() protoreflect.Message {
	mi := &file_shep_optimizer_shep_optimizer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartOptimizerReply.ProtoReflect.Descriptor instead.
func (*StartOptimizerReply) Descriptor() ([]byte, []int) {
	return file_shep_optimizer_shep_optimizer_proto_rawDescGZIP(), []int{3}
}

func (x *StartOptimizerReply) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

type StopOptimizerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopOptimizerRequest) Reset() {
	*x = StopOptimizerRequest{}
	mi := &file_shep_optimizer_shep_optimizer_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopOptimizerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopOptimizerRequest) ProtoMessage() {}

func (x *StopOptimizerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shep_optimizer_shep_optimizer_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopOptimizerRequest.ProtoReflect.Descriptor instead.
func (*StopOptimizerRequest) Descriptor() ([]byte, []int) {
	return file_shep_optimizer_shep_optimizer_proto_rawDescGZIP(), []int{4}
}

type StopOptimizerReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Done          bool                   `protobuf:"varint,1,opt,name=done,proto3" json:"done,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopOptimizerReply) Reset() {
	*x = StopOptimizerReply{}
	mi := &file_shep_optimizer_shep_optimizer_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopOptimizerReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopOptimizerReply) ProtoMessage() {}

func (x *StopOptimizerReply) ProtoReflect() protoreflect.Message {
	mi := &file_shep_optimizer_shep_optimizer_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopOptimizerReply.ProtoReflect.Descriptor instead.
func (*StopOptimizerReply) Descriptor() ([]byte, []int) {
	return file_shep_optimizer_shep_optimizer_proto_rawDescGZIP(), []int{5}
}

func (x *StopOptimizerReply) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

type OptimizeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ctrls         []*ControlEntry        `protobuf:"bytes,1,rep,name=ctrls,proto3" json:"ctrls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OptimizeRequest) Reset() {
	*x = OptimizeRequest{}
	mi := &file_shep_optimizer_shep_optimizer_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OptimizeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OptimizeRequest) ProtoMessage() {}

func (x *OptimizeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shep_optimizer_shep_optimizer_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OptimizeRequest.ProtoReflect.Descriptor instead.
func (*OptimizeRequest) Descriptor() ([]byte, []int) {
	return file_shep_optimizer_shep_optimizer_proto_rawDescGZIP(), []int{6}
}

func (x *OptimizeRequest) GetCtrls() []*ControlEntry {
	if x != nil {
		return x.Ctrls
	}
	return nil
}

type OptimizeReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Done          bool                   `protobuf:"varint,1,opt,name=done,proto3" json:"done,omitempty"`
	Rewards       []*RewardEntry         `protobuf:"bytes,2,rep,name=rewards,proto3" json:"rewards,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OptimizeReply) Reset() {
	*x = OptimizeReply{}
	mi := &file_shep_optimizer_shep_optimizer_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OptimizeReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OptimizeReply) ProtoMessage() {}

func (x *OptimizeReply) ProtoReflect() protoreflect.Message {
	mi := &file_shep_optimizer_shep_optimizer_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OptimizeReply.ProtoReflect.Descriptor instead.
func (*OptimizeReply) Descriptor() ([]byte, []int) {
	return file_shep_optimizer_shep_optimizer_proto_rawDescGZIP(), []int{7}
}

func (x *OptimizeReply) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

func (x *OptimizeReply) GetRewards() []*RewardEntry {
	if x != nil {
		return x.Rewards
	}
	return nil
}

var File_shep_optimizer_shep_optimizer_proto protoreflect.FileDescriptor

var file_shep_optimizer_shep_optimizer_proto_rawDesc = string([]byte{
	0x0a, 0x23, 0x73, 0x68, 0x65, 0x70, 0x5f, 0x6f, 0x70, 0x74, 0x69, 0x6d, 0x69, 0x7a, 0x65, 0x72,
	0x2f, 0x73, 0x68, 0x65, 0x70, 0x5f, 0x6f, 0x70, 0x74, 0x69, 0x6d, 0x69, 0x7a, 0x65, 0x72, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x73, 0x68, 0x65, 0x70, 0x68, 0x65, 0x72, 0x64, 0x22,
	0x34, 0x0a, 0x0c, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12,
	0x12, 0x0a, 0x04, 0x6b, 0x6e, 0x6f, 0x62, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6b,
	0x6e, 0x6f, 0x62, 0x12, 0x10, 0x0a, 0x03, 0x76, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x03, 0x76, 0x61, 0x6c, 0x22, 0x2f, 0x0a, 0x0b, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64, 0x45,
	0x6e, 0x74, 0x72, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x76, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x02, 0x52, 0x03, 0x76, 0x61, 0x6c, 0x22, 0x32, 0x0a, 0x15, 0x53, 0x74, 0x61, 0x72, 0x74, 0x4f,
	0x70, 0x74, 0x69, 0x6d, 0x69, 0x7a, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x19, 0x0a, 0x08, 0x6e, 0x5f, 0x74, 0x72, 0x69, 0x61, 0x6c, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x07, 0x6e, 0x54, 0x72, 0x69, 0x61, 0x6c, 0x73, 0x22, 0x29, 0x0a, 0x13, 0x53, 0x74,
	0x61, 0x72, 0x74, 0x4f, 0x70, 0x74, 0x69, 0x6d, 0x69, 0x7a, 0x65, 0x72, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x6f, 0x6e, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x04, 0x64, 0x6f, 0x6e, 0x65, 0x22, 0x16, 0x0a, 0x14, 0x53, 0x74, 0x6f, 0x70, 0x4f, 0x70, 0x74,
	0x69, 0x6d, 0x69, 0x7a, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x28, 0x0a,
	0x12, 0x53, 0x74, 0x6f, 0x70, 0x4f, 0x70, 0x74, 0x69, 0x6d, 0x69, 0x7a, 0x65, 0x72, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x6f, 0x6e, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x04, 0x64, 0x6f, 0x6e, 0x65, 0x22, 0x3f, 0x0a, 0x0f, 0x4f, 0x70, 0x74, 0x69, 0x6d,
	0x69, 0x7a, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2c, 0x0a, 0x05, 0x63, 0x74,
	0x72, 0x6c, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x73, 0x68, 0x65, 0x70,
	0x68, 0x65, 0x72, 0x64, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x45, 0x6e, 0x74, 0x72,
	0x79, 0x52, 0x05, 0x63, 0x74, 0x72, 0x6c, 0x73, 0x22, 0x54, 0x0a, 0x0d, 0x4f, 0x70, 0x74, 0x69,
	0x6d, 0x69, 0x7a, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x6f, 0x6e,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x64, 0x6f, 0x6e, 0x65, 0x12, 0x2f, 0x0a,
	0x07, 0x72, 0x65, 0x77, 0x61, 0x72, 0x64, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15,
	0x2e, 0x73, 0x68, 0x65, 0x70, 0x68, 0x65, 0x72, 0x64, 0x2e, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64,
	0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x07, 0x72, 0x65, 0x77, 0x61, 0x72, 0x64, 0x73, 0x32, 0xb0,
	0x01, 0x0a, 0x0d, 0x53, 0x65, 0x74, 0x75, 0x70, 0x4f, 0x70, 0x74, 0x69, 0x6d, 0x69, 0x7a, 0x65,
	0x12, 0x50, 0x0a, 0x0e, 0x53, 0x74, 0x61, 0x72, 0x74, 0x4f, 0x70, 0x74, 0x69, 0x6d, 0x69, 0x7a,
	0x65, 0x72, 0x12, 0x1f, 0x2e, 0x73, 0x68, 0x65, 0x70, 0x68, 0x65, 0x72, 0x64, 0x2e, 0x53, 0x74,
	0x61, 0x72, 0x74, 0x4f, 0x70, 0x74, 0x69, 0x6d, 0x69, 0x7a, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x73, 0x68, 0x65, 0x70, 0x68, 0x65, 0x72, 0x64, 0x2e, 0x53,
	0x74, 0x61, 0x72, 0x74, 0x4f, 0x70, 0x74, 0x69, 0x6d, 0x69, 0x7a, 0x65, 0x72, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x12, 0x4d, 0x0a, 0x0d, 0x53, 0x74, 0x6f, 0x70, 0x4f, 0x70, 0x74, 0x69, 0x6d, 0x69,
	0x7a, 0x65, 0x72, 0x12, 0x1e, 0x2e, 0x73, 0x68, 0x65, 0x70, 0x68, 0x65, 0x72, 0x64, 0x2e, 0x53,
	0x74, 0x6f, 0x70, 0x4f, 0x70, 0x74, 0x69, 0x6d, 0x69, 0x7a, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x73, 0x68, 0x65, 0x70, 0x68, 0x65, 0x72, 0x64, 0x2e, 0x53,
	0x74, 0x6f, 0x70, 0x4f, 0x70, 0x74, 0x69, 0x6d, 0x69, 0x7a, 0x65, 0x72, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x32, 0x53, 0x0a, 0x08, 0x4f, 0x70, 0x74, 0x69, 0x6d, 0x69, 0x7a, 0x65, 0x12, 0x47, 0x0a,
	0x11, 0x45, 0x76, 0x61, 0x6c, 0x75, 0x61, 0x74, 0x65, 0x4f, 0x70, 0x74, 0x69, 0x6d, 0x69, 0x7a,
	0x65, 0x72, 0x12, 0x19, 0x2e, 0x73, 0x68, 0x65, 0x70, 0x68, 0x65, 0x72, 0x64, 0x2e, 0x4f, 0x70,
	0x74, 0x69, 0x6d, 0x69, 0x7a, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e,
	0x73, 0x68, 0x65, 0x70, 0x68, 0x65, 0x72, 0x64, 0x2e, 0x4f, 0x70, 0x74, 0x69, 0x6d, 0x69, 0x7a,
	0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x42, 0x26, 0x5a, 0x24, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x77, 0x61, 0x64, 0x79, 0x6e, 0x2f, 0x73, 0x68, 0x65, 0x70,
	0x5f, 0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x5f, 0x6d, 0x75, 0x73, 0x74, 0x65, 0x72, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_shep_optimizer_shep_optimizer_proto_rawDescOnce sync.Once
	file_shep_optimizer_shep_optimizer_proto_rawDescData []byte
)

func file_shep_optimizer_shep_optimizer_proto_rawDescGZIP() []byte {
	file_shep_optimizer_shep_optimizer_proto_rawDescOnce.Do(func() {
		file_shep_optimizer_shep_optimizer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shep_optimizer_shep_optimizer_proto_rawDesc), len(file_shep_optimizer_shep_optimizer_proto_rawDesc)))
	})
	return file_shep_optimizer_shep_optimizer_proto_rawDescData
}

var file_shep_optimizer_shep_optimizer_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_shep_optimizer_shep_optimizer_proto_goTypes = []any{
	(*ControlEntry)(nil),          // 0: shepherd.ControlEntry
	(*RewardEntry)(nil),           // 1: shepherd.RewardEntry
	(*StartOptimizerRequest)(nil), // 2: shepherd.StartOptimizerRequest
	(*StartOptimizerReply)(nil),   // 3: shepherd.StartOptimizerReply
	(*StopOptimizerRequest)(nil),  // 4: shepherd.StopOptimizerRequest
	(*StopOptimizerReply)(nil),    // 5: shepherd.StopOptimizerReply
	(*OptimizeRequest)(nil),       // 6: shepherd.OptimizeRequest
	(*OptimizeReply)(nil),         // 7: shepherd.OptimizeReply
}
var file_shep_optimizer_shep_optimizer_proto_depIdxs = []int32{
	0, // 0: shepherd.OptimizeRequest.ctrls:type_name -> shepherd.ControlEntry
	1, // 1: shepherd.OptimizeReply.rewards:type_name -> shepherd.RewardEntry
	2, // 2: shepherd.SetupOptimize.StartOptimizer:input_type -> shepherd.StartOptimizerRequest
	4, // 3: shepherd.SetupOptimize.StopOptimizer:input_type -> shepherd.StopOptimizerRequest
	6, // 4: shepherd.Optimize.EvaluateOptimizer:input_type -> shepherd.OptimizeRequest
	3, // 5: shepherd.SetupOptimize.StartOptimizer:output_type -> shepherd.StartOptimizerReply
	5, // 6: shepherd.SetupOptimize.StopOptimizer:output_type -> shepherd.StopOptimizerReply
	7, // 7: shepherd.Optimize.EvaluateOptimizer:output_type -> shepherd.OptimizeReply
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_shep_optimizer_shep_optimizer_proto_init() }
func file_shep_optimizer_shep_optimizer_proto_init() {
	if File_shep_optimizer_shep_optimizer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shep_optimizer_shep_optimizer_proto_rawDesc), len(file_shep_optimizer_shep_optimizer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_shep_optimizer_shep_optimizer_proto_goTypes,
		DependencyIndexes: file_shep_optimizer_shep_optimizer_proto_depIdxs,
		MessageInfos:      file_shep_optimizer_shep_optimizer_proto_msgTypes,
	}.Build()
	File_shep_optimizer_shep_optimizer_proto = out.File
	file_shep_optimizer_shep_optimizer_proto_goTypes = nil
	file_shep_optimizer_shep_optimizer_proto_depIdxs = nil
}
