// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: shep_optimizer/shep_optimizer.proto

package shep_remote_muster

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Optimize_StartOptimizer_FullMethodName = "/shepherd.Optimize/StartOptimizer"
)

// OptimizeClient is the client API for Optimize service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OptimizeClient interface {
	StartOptimizer(ctx context.Context, in *StartOptimizerRequest, opts ...grpc.CallOption) (*StartOptimizerReply, error)
}

type optimizeClient struct {
	cc grpc.ClientConnInterface
}

func NewOptimizeClient(cc grpc.ClientConnInterface) OptimizeClient {
	return &optimizeClient{cc}
}

func (c *optimizeClient) StartOptimizer(ctx context.Context, in *StartOptimizerRequest, opts ...grpc.CallOption) (*StartOptimizerReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartOptimizerReply)
	err := c.cc.Invoke(ctx, Optimize_StartOptimizer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OptimizeServer is the server API for Optimize service.
// All implementations must embed UnimplementedOptimizeServer
// for forward compatibility.
type OptimizeServer interface {
	StartOptimizer(context.Context, *StartOptimizerRequest) (*StartOptimizerReply, error)
	mustEmbedUnimplementedOptimizeServer()
}

// UnimplementedOptimizeServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOptimizeServer struct{}

func (UnimplementedOptimizeServer) StartOptimizer(context.Context, *StartOptimizerRequest) (*StartOptimizerReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartOptimizer not implemented")
}
func (UnimplementedOptimizeServer) mustEmbedUnimplementedOptimizeServer() {}
func (UnimplementedOptimizeServer) testEmbeddedByValue()                  {}

// UnsafeOptimizeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OptimizeServer will
// result in compilation errors.
type UnsafeOptimizeServer interface {
	mustEmbedUnimplementedOptimizeServer()
}

func RegisterOptimizeServer(s grpc.ServiceRegistrar, srv OptimizeServer) {
	// If the following call pancis, it indicates UnimplementedOptimizeServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Optimize_ServiceDesc, srv)
}

func _Optimize_StartOptimizer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartOptimizerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OptimizeServer).StartOptimizer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Optimize_StartOptimizer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OptimizeServer).StartOptimizer(ctx, req.(*StartOptimizerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Optimize_ServiceDesc is the grpc.ServiceDesc for Optimize service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Optimize_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "shepherd.Optimize",
	HandlerType: (*OptimizeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartOptimizer",
			Handler:    _Optimize_StartOptimizer_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "shep_optimizer/shep_optimizer.proto",
}
