// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: shep_optimizer/shep_optimizer.proto

package shep_remote_muster

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SetupOptimize_StartOptimizer_FullMethodName = "/shepherd.SetupOptimize/StartOptimizer"
	SetupOptimize_StopOptimizer_FullMethodName  = "/shepherd.SetupOptimize/StopOptimizer"
)

// SetupOptimizeClient is the client API for SetupOptimize service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SetupOptimizeClient interface {
	StartOptimizer(ctx context.Context, in *StartOptimizerRequest, opts ...grpc.CallOption) (*StartOptimizerReply, error)
	StopOptimizer(ctx context.Context, in *StopOptimizerRequest, opts ...grpc.CallOption) (*StopOptimizerReply, error)
}

type setupOptimizeClient struct {
	cc grpc.ClientConnInterface
}

func NewSetupOptimizeClient(cc grpc.ClientConnInterface) SetupOptimizeClient {
	return &setupOptimizeClient{cc}
}

func (c *setupOptimizeClient) StartOptimizer(ctx context.Context, in *StartOptimizerRequest, opts ...grpc.CallOption) (*StartOptimizerReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartOptimizerReply)
	err := c.cc.Invoke(ctx, SetupOptimize_StartOptimizer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *setupOptimizeClient) StopOptimizer(ctx context.Context, in *StopOptimizerRequest, opts ...grpc.CallOption) (*StopOptimizerReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StopOptimizerReply)
	err := c.cc.Invoke(ctx, SetupOptimize_StopOptimizer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SetupOptimizeServer is the server API for SetupOptimize service.
// All implementations must embed UnimplementedSetupOptimizeServer
// for forward compatibility.
type SetupOptimizeServer interface {
	StartOptimizer(context.Context, *StartOptimizerRequest) (*StartOptimizerReply, error)
	StopOptimizer(context.Context, *StopOptimizerRequest) (*StopOptimizerReply, error)
	mustEmbedUnimplementedSetupOptimizeServer()
}

// UnimplementedSetupOptimizeServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSetupOptimizeServer struct{}

func (UnimplementedSetupOptimizeServer) StartOptimizer(context.Context, *StartOptimizerRequest) (*StartOptimizerReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartOptimizer not implemented")
}
func (UnimplementedSetupOptimizeServer) StopOptimizer(context.Context, *StopOptimizerRequest) (*StopOptimizerReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StopOptimizer not implemented")
}
func (UnimplementedSetupOptimizeServer) mustEmbedUnimplementedSetupOptimizeServer() {}
func (UnimplementedSetupOptimizeServer) testEmbeddedByValue()                       {}

// UnsafeSetupOptimizeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SetupOptimizeServer will
// result in compilation errors.
type UnsafeSetupOptimizeServer interface {
	mustEmbedUnimplementedSetupOptimizeServer()
}

func RegisterSetupOptimizeServer(s grpc.ServiceRegistrar, srv SetupOptimizeServer) {
	// If the following call pancis, it indicates UnimplementedSetupOptimizeServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SetupOptimize_ServiceDesc, srv)
}

func _SetupOptimize_StartOptimizer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartOptimizerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SetupOptimizeServer).StartOptimizer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SetupOptimize_StartOptimizer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SetupOptimizeServer).StartOptimizer(ctx, req.(*StartOptimizerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SetupOptimize_StopOptimizer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopOptimizerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SetupOptimizeServer).StopOptimizer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SetupOptimize_StopOptimizer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SetupOptimizeServer).StopOptimizer(ctx, req.(*StopOptimizerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SetupOptimize_ServiceDesc is the grpc.ServiceDesc for SetupOptimize service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SetupOptimize_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "shepherd.SetupOptimize",
	HandlerType: (*SetupOptimizeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartOptimizer",
			Handler:    _SetupOptimize_StartOptimizer_Handler,
		},
		{
			MethodName: "StopOptimizer",
			Handler:    _SetupOptimize_StopOptimizer_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "shep_optimizer/shep_optimizer.proto",
}

const (
	Optimize_EvaluateOptimizer_FullMethodName = "/shepherd.Optimize/EvaluateOptimizer"
)

// OptimizeClient is the client API for Optimize service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OptimizeClient interface {
	EvaluateOptimizer(ctx context.Context, in *OptimizeRequest, opts ...grpc.CallOption) (*OptimizeReply, error)
}

type optimizeClient struct {
	cc grpc.ClientConnInterface
}

func NewOptimizeClient(cc grpc.ClientConnInterface) OptimizeClient {
	return &optimizeClient{cc}
}

func (c *optimizeClient) EvaluateOptimizer(ctx context.Context, in *OptimizeRequest, opts ...grpc.CallOption) (*OptimizeReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OptimizeReply)
	err := c.cc.Invoke(ctx, Optimize_EvaluateOptimizer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OptimizeServer is the server API for Optimize service.
// All implementations must embed UnimplementedOptimizeServer
// for forward compatibility.
type OptimizeServer interface {
	EvaluateOptimizer(context.Context, *OptimizeRequest) (*OptimizeReply, error)
	mustEmbedUnimplementedOptimizeServer()
}

// UnimplementedOptimizeServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOptimizeServer struct{}

func (UnimplementedOptimizeServer) EvaluateOptimizer(context.Context, *OptimizeRequest) (*OptimizeReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EvaluateOptimizer not implemented")
}
func (UnimplementedOptimizeServer) mustEmbedUnimplementedOptimizeServer() {}
func (UnimplementedOptimizeServer) testEmbeddedByValue()                  {}

// UnsafeOptimizeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OptimizeServer will
// result in compilation errors.
type UnsafeOptimizeServer interface {
	mustEmbedUnimplementedOptimizeServer()
}

func RegisterOptimizeServer(s grpc.ServiceRegistrar, srv OptimizeServer) {
	// If the following call pancis, it indicates UnimplementedOptimizeServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Optimize_ServiceDesc, srv)
}

func _Optimize_EvaluateOptimizer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OptimizeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OptimizeServer).EvaluateOptimizer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Optimize_EvaluateOptimizer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OptimizeServer).EvaluateOptimizer(ctx, req.(*OptimizeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Optimize_ServiceDesc is the grpc.ServiceDesc for Optimize service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Optimize_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "shepherd.Optimize",
	HandlerType: (*OptimizeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "EvaluateOptimizer",
			Handler:    _Optimize_EvaluateOptimizer_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "shep_optimizer/shep_optimizer.proto",
}
