# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from shep_optimizer import shep_optimizer_pb2 as shep__optimizer_dot_shep__optimizer__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in shep_optimizer/shep_optimizer_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SetupOptimizeStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StartOptimizer = channel.unary_unary(
                '/shepherd.SetupOptimize/StartOptimizer',
                request_serializer=shep__optimizer_dot_shep__optimizer__pb2.StartOptimizerRequest.SerializeToString,
                response_deserializer=shep__optimizer_dot_shep__optimizer__pb2.StartOptimizerReply.FromString,
                _registered_method=True)
        self.StopOptimizer = channel.unary_unary(
                '/shepherd.SetupOptimize/StopOptimizer',
                request_serializer=shep__optimizer_dot_shep__optimizer__pb2.StopOptimizerRequest.SerializeToString,
                response_deserializer=shep__optimizer_dot_shep__optimizer__pb2.StopOptimizerReply.FromString,
                _registered_method=True)


class SetupOptimizeServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StartOptimizer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopOptimizer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SetupOptimizeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StartOptimizer': grpc.unary_unary_rpc_method_handler(
                    servicer.StartOptimizer,
                    request_deserializer=shep__optimizer_dot_shep__optimizer__pb2.StartOptimizerRequest.FromString,
                    response_serializer=shep__optimizer_dot_shep__optimizer__pb2.StartOptimizerReply.SerializeToString,
            ),
            'StopOptimizer': grpc.unary_unary_rpc_method_handler(
                    servicer.StopOptimizer,
                    request_deserializer=shep__optimizer_dot_shep__optimizer__pb2.StopOptimizerRequest.FromString,
                    response_serializer=shep__optimizer_dot_shep__optimizer__pb2.StopOptimizerReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'shepherd.SetupOptimize', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('shepherd.SetupOptimize', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SetupOptimize(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StartOptimizer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/shepherd.SetupOptimize/StartOptimizer',
            shep__optimizer_dot_shep__optimizer__pb2.StartOptimizerRequest.SerializeToString,
            shep__optimizer_dot_shep__optimizer__pb2.StartOptimizerReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StopOptimizer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/shepherd.SetupOptimize/StopOptimizer',
            shep__optimizer_dot_shep__optimizer__pb2.StopOptimizerRequest.SerializeToString,
            shep__optimizer_dot_shep__optimizer__pb2.StopOptimizerReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class OptimizeStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.EvaluateOptimizer = channel.unary_unary(
                '/shepherd.Optimize/EvaluateOptimizer',
                request_serializer=shep__optimizer_dot_shep__optimizer__pb2.OptimizeRequest.SerializeToString,
                response_deserializer=shep__optimizer_dot_shep__optimizer__pb2.OptimizeReply.FromString,
                _registered_method=True)


class OptimizeServicer(object):
    """Missing associated documentation comment in .proto file."""

    def EvaluateOptimizer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OptimizeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'EvaluateOptimizer': grpc.unary_unary_rpc_method_handler(
                    servicer.EvaluateOptimizer,
                    request_deserializer=shep__optimizer_dot_shep__optimizer__pb2.OptimizeRequest.FromString,
                    response_serializer=shep__optimizer_dot_shep__optimizer__pb2.OptimizeReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'shepherd.Optimize', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('shepherd.Optimize', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Optimize(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def EvaluateOptimizer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/shepherd.Optimize/EvaluateOptimizer',
            shep__optimizer_dot_shep__optimizer__pb2.OptimizeRequest.SerializeToString,
            shep__optimizer_dot_shep__optimizer__pb2.OptimizeReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
