# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: shep_log_processor/shep_log_processor.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'shep_log_processor/shep_log_processor.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n+shep_log_processor/shep_log_processor.proto\x12\x08shepherd\x1a\x19google/protobuf/any.proto\"7\n\x11ProcessLogRequest\x12\"\n\x04\x61rgs\x18\x01 \x03(\x0b\x32\x14.google.protobuf.Any\"\x1f\n\x0fProcessLogReply\x12\x0c\n\x04\x64one\x18\x01 \x01(\x08\";\n\x15StartOptimizerRequest\x12\"\n\x04\x61rgs\x18\x01 \x03(\x0b\x32\x14.google.protobuf.Any\"#\n\x13StartOptimizerReply\x12\x0c\n\x04\x64one\x18\x01 \x01(\x08\"=\n\x17\x45valuateLogStatsRequest\x12\"\n\x04\x61rgs\x18\x01 \x03(\x0b\x32\x14.google.protobuf.Any\"%\n\x15\x45valuateLogStatsReply\x12\x0c\n\x04\x64one\x18\x01 \x01(\x08\x32\xa6\x01\n\x0cLogProcessor\x12P\n\x0eStartOptimizer\x12\x1f.shepherd.StartOptimizerRequest\x1a\x1d.shepherd.StartOptimizerReply\x12\x44\n\nProcessLog\x12\x1b.shepherd.ProcessLogRequest\x1a\x19.shepherd.ProcessLogReply2k\n\x11LogStatsMessenger\x12V\n\x10\x45valuateLogStats\x12!.shepherd.EvaluateLogStatsRequest\x1a\x1f.shepherd.EvaluateLogStatsReplyB&Z$github.com/awadyn/shep_remote_musterb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'shep_log_processor.shep_log_processor_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z$github.com/awadyn/shep_remote_muster'
  _globals['_PROCESSLOGREQUEST']._serialized_start=84
  _globals['_PROCESSLOGREQUEST']._serialized_end=139
  _globals['_PROCESSLOGREPLY']._serialized_start=141
  _globals['_PROCESSLOGREPLY']._serialized_end=172
  _globals['_STARTOPTIMIZERREQUEST']._serialized_start=174
  _globals['_STARTOPTIMIZERREQUEST']._serialized_end=233
  _globals['_STARTOPTIMIZERREPLY']._serialized_start=235
  _globals['_STARTOPTIMIZERREPLY']._serialized_end=270
  _globals['_EVALUATELOGSTATSREQUEST']._serialized_start=272
  _globals['_EVALUATELOGSTATSREQUEST']._serialized_end=333
  _globals['_EVALUATELOGSTATSREPLY']._serialized_start=335
  _globals['_EVALUATELOGSTATSREPLY']._serialized_end=372
  _globals['_LOGPROCESSOR']._serialized_start=375
  _globals['_LOGPROCESSOR']._serialized_end=541
  _globals['_LOGSTATSMESSENGER']._serialized_start=543
  _globals['_LOGSTATSMESSENGER']._serialized_end=650
# @@protoc_insertion_point(module_scope)
