// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.12.4
// source: shep_log_processor/shep_log_processor.proto

package shep_remote_muster

import (
	any1 "github.com/golang/protobuf/ptypes/any"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProcessLogRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Args []*any1.Any `protobuf:"bytes,1,rep,name=args,proto3" json:"args,omitempty"`
}

func (x *ProcessLogRequest) Reset() {
	*x = ProcessLogRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shep_log_processor_shep_log_processor_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProcessLogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessLogRequest) ProtoMessage() {}

func (x *ProcessLogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shep_log_processor_shep_log_processor_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessLogRequest.ProtoReflect.Descriptor instead.
func (*ProcessLogRequest) Descriptor() ([]byte, []int) {
	return file_shep_log_processor_shep_log_processor_proto_rawDescGZIP(), []int{0}
}

func (x *ProcessLogRequest) GetArgs() []*any1.Any {
	if x != nil {
		return x.Args
	}
	return nil
}

type ProcessLogReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Done bool `protobuf:"varint,1,opt,name=done,proto3" json:"done,omitempty"`
}

func (x *ProcessLogReply) Reset() {
	*x = ProcessLogReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shep_log_processor_shep_log_processor_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProcessLogReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessLogReply) ProtoMessage() {}

func (x *ProcessLogReply) ProtoReflect() protoreflect.Message {
	mi := &file_shep_log_processor_shep_log_processor_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessLogReply.ProtoReflect.Descriptor instead.
func (*ProcessLogReply) Descriptor() ([]byte, []int) {
	return file_shep_log_processor_shep_log_processor_proto_rawDescGZIP(), []int{1}
}

func (x *ProcessLogReply) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

type StartOptimizerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Args []*any1.Any `protobuf:"bytes,1,rep,name=args,proto3" json:"args,omitempty"`
}

func (x *StartOptimizerRequest) Reset() {
	*x = StartOptimizerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shep_log_processor_shep_log_processor_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartOptimizerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartOptimizerRequest) ProtoMessage() {}

func (x *StartOptimizerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shep_log_processor_shep_log_processor_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartOptimizerRequest.ProtoReflect.Descriptor instead.
func (*StartOptimizerRequest) Descriptor() ([]byte, []int) {
	return file_shep_log_processor_shep_log_processor_proto_rawDescGZIP(), []int{2}
}

func (x *StartOptimizerRequest) GetArgs() []*any1.Any {
	if x != nil {
		return x.Args
	}
	return nil
}

type StartOptimizerReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Done bool `protobuf:"varint,1,opt,name=done,proto3" json:"done,omitempty"`
}

func (x *StartOptimizerReply) Reset() {
	*x = StartOptimizerReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shep_log_processor_shep_log_processor_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartOptimizerReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartOptimizerReply) ProtoMessage() {}

func (x *StartOptimizerReply) ProtoReflect() protoreflect.Message {
	mi := &file_shep_log_processor_shep_log_processor_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartOptimizerReply.ProtoReflect.Descriptor instead.
func (*StartOptimizerReply) Descriptor() ([]byte, []int) {
	return file_shep_log_processor_shep_log_processor_proto_rawDescGZIP(), []int{3}
}

func (x *StartOptimizerReply) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

type EvaluateLogStatsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Args []*any1.Any `protobuf:"bytes,1,rep,name=args,proto3" json:"args,omitempty"`
}

func (x *EvaluateLogStatsRequest) Reset() {
	*x = EvaluateLogStatsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shep_log_processor_shep_log_processor_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EvaluateLogStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvaluateLogStatsRequest) ProtoMessage() {}

func (x *EvaluateLogStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shep_log_processor_shep_log_processor_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvaluateLogStatsRequest.ProtoReflect.Descriptor instead.
func (*EvaluateLogStatsRequest) Descriptor() ([]byte, []int) {
	return file_shep_log_processor_shep_log_processor_proto_rawDescGZIP(), []int{4}
}

func (x *EvaluateLogStatsRequest) GetArgs() []*any1.Any {
	if x != nil {
		return x.Args
	}
	return nil
}

type EvaluateLogStatsReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Done bool `protobuf:"varint,1,opt,name=done,proto3" json:"done,omitempty"`
}

func (x *EvaluateLogStatsReply) Reset() {
	*x = EvaluateLogStatsReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shep_log_processor_shep_log_processor_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EvaluateLogStatsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvaluateLogStatsReply) ProtoMessage() {}

func (x *EvaluateLogStatsReply) ProtoReflect() protoreflect.Message {
	mi := &file_shep_log_processor_shep_log_processor_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvaluateLogStatsReply.ProtoReflect.Descriptor instead.
func (*EvaluateLogStatsReply) Descriptor() ([]byte, []int) {
	return file_shep_log_processor_shep_log_processor_proto_rawDescGZIP(), []int{5}
}

func (x *EvaluateLogStatsReply) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

var File_shep_log_processor_shep_log_processor_proto protoreflect.FileDescriptor

var file_shep_log_processor_shep_log_processor_proto_rawDesc = []byte{
	0x0a, 0x2b, 0x73, 0x68, 0x65, 0x70, 0x5f, 0x6c, 0x6f, 0x67, 0x5f, 0x70, 0x72, 0x6f, 0x63, 0x65,
	0x73, 0x73, 0x6f, 0x72, 0x2f, 0x73, 0x68, 0x65, 0x70, 0x5f, 0x6c, 0x6f, 0x67, 0x5f, 0x70, 0x72,
	0x6f, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x73,
	0x68, 0x65, 0x70, 0x68, 0x65, 0x72, 0x64, 0x1a, 0x19, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x61, 0x6e, 0x79, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x3d, 0x0a, 0x11, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x4c, 0x6f, 0x67,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x28, 0x0a, 0x04, 0x61, 0x72, 0x67, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41, 0x6e, 0x79, 0x52, 0x04, 0x61, 0x72, 0x67,
	0x73, 0x22, 0x25, 0x0a, 0x0f, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x4c, 0x6f, 0x67, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x6f, 0x6e, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x04, 0x64, 0x6f, 0x6e, 0x65, 0x22, 0x41, 0x0a, 0x15, 0x53, 0x74, 0x61, 0x72,
	0x74, 0x4f, 0x70, 0x74, 0x69, 0x6d, 0x69, 0x7a, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x28, 0x0a, 0x04, 0x61, 0x72, 0x67, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x14, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x41, 0x6e, 0x79, 0x52, 0x04, 0x61, 0x72, 0x67, 0x73, 0x22, 0x29, 0x0a, 0x13, 0x53,
	0x74, 0x61, 0x72, 0x74, 0x4f, 0x70, 0x74, 0x69, 0x6d, 0x69, 0x7a, 0x65, 0x72, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x6f, 0x6e, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x04, 0x64, 0x6f, 0x6e, 0x65, 0x22, 0x43, 0x0a, 0x17, 0x45, 0x76, 0x61, 0x6c, 0x75, 0x61,
	0x74, 0x65, 0x4c, 0x6f, 0x67, 0x53, 0x74, 0x61, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x28, 0x0a, 0x04, 0x61, 0x72, 0x67, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x14, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x41, 0x6e, 0x79, 0x52, 0x04, 0x61, 0x72, 0x67, 0x73, 0x22, 0x2b, 0x0a, 0x15, 0x45,
	0x76, 0x61, 0x6c, 0x75, 0x61, 0x74, 0x65, 0x4c, 0x6f, 0x67, 0x53, 0x74, 0x61, 0x74, 0x73, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x6f, 0x6e, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x04, 0x64, 0x6f, 0x6e, 0x65, 0x32, 0xa6, 0x01, 0x0a, 0x0c, 0x4c, 0x6f, 0x67,
	0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x12, 0x50, 0x0a, 0x0e, 0x53, 0x74, 0x61,
	0x72, 0x74, 0x4f, 0x70, 0x74, 0x69, 0x6d, 0x69, 0x7a, 0x65, 0x72, 0x12, 0x1f, 0x2e, 0x73, 0x68,
	0x65, 0x70, 0x68, 0x65, 0x72, 0x64, 0x2e, 0x53, 0x74, 0x61, 0x72, 0x74, 0x4f, 0x70, 0x74, 0x69,
	0x6d, 0x69, 0x7a, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x73,
	0x68, 0x65, 0x70, 0x68, 0x65, 0x72, 0x64, 0x2e, 0x53, 0x74, 0x61, 0x72, 0x74, 0x4f, 0x70, 0x74,
	0x69, 0x6d, 0x69, 0x7a, 0x65, 0x72, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x44, 0x0a, 0x0a, 0x50,
	0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x4c, 0x6f, 0x67, 0x12, 0x1b, 0x2e, 0x73, 0x68, 0x65, 0x70,
	0x68, 0x65, 0x72, 0x64, 0x2e, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x4c, 0x6f, 0x67, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x73, 0x68, 0x65, 0x70, 0x68, 0x65, 0x72,
	0x64, 0x2e, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x4c, 0x6f, 0x67, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x32, 0x6b, 0x0a, 0x11, 0x4c, 0x6f, 0x67, 0x53, 0x74, 0x61, 0x74, 0x73, 0x4d, 0x65, 0x73,
	0x73, 0x65, 0x6e, 0x67, 0x65, 0x72, 0x12, 0x56, 0x0a, 0x10, 0x45, 0x76, 0x61, 0x6c, 0x75, 0x61,
	0x74, 0x65, 0x4c, 0x6f, 0x67, 0x53, 0x74, 0x61, 0x74, 0x73, 0x12, 0x21, 0x2e, 0x73, 0x68, 0x65,
	0x70, 0x68, 0x65, 0x72, 0x64, 0x2e, 0x45, 0x76, 0x61, 0x6c, 0x75, 0x61, 0x74, 0x65, 0x4c, 0x6f,
	0x67, 0x53, 0x74, 0x61, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e,
	0x73, 0x68, 0x65, 0x70, 0x68, 0x65, 0x72, 0x64, 0x2e, 0x45, 0x76, 0x61, 0x6c, 0x75, 0x61, 0x74,
	0x65, 0x4c, 0x6f, 0x67, 0x53, 0x74, 0x61, 0x74, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x42, 0x26,
	0x5a, 0x24, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x77, 0x61,
	0x64, 0x79, 0x6e, 0x2f, 0x73, 0x68, 0x65, 0x70, 0x5f, 0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x5f,
	0x6d, 0x75, 0x73, 0x74, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_shep_log_processor_shep_log_processor_proto_rawDescOnce sync.Once
	file_shep_log_processor_shep_log_processor_proto_rawDescData = file_shep_log_processor_shep_log_processor_proto_rawDesc
)

func file_shep_log_processor_shep_log_processor_proto_rawDescGZIP() []byte {
	file_shep_log_processor_shep_log_processor_proto_rawDescOnce.Do(func() {
		file_shep_log_processor_shep_log_processor_proto_rawDescData = protoimpl.X.CompressGZIP(file_shep_log_processor_shep_log_processor_proto_rawDescData)
	})
	return file_shep_log_processor_shep_log_processor_proto_rawDescData
}

var file_shep_log_processor_shep_log_processor_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_shep_log_processor_shep_log_processor_proto_goTypes = []interface{}{
	(*ProcessLogRequest)(nil),       // 0: shepherd.ProcessLogRequest
	(*ProcessLogReply)(nil),         // 1: shepherd.ProcessLogReply
	(*StartOptimizerRequest)(nil),   // 2: shepherd.StartOptimizerRequest
	(*StartOptimizerReply)(nil),     // 3: shepherd.StartOptimizerReply
	(*EvaluateLogStatsRequest)(nil), // 4: shepherd.EvaluateLogStatsRequest
	(*EvaluateLogStatsReply)(nil),   // 5: shepherd.EvaluateLogStatsReply
	(*any1.Any)(nil),                // 6: google.protobuf.Any
}
var file_shep_log_processor_shep_log_processor_proto_depIdxs = []int32{
	6, // 0: shepherd.ProcessLogRequest.args:type_name -> google.protobuf.Any
	6, // 1: shepherd.StartOptimizerRequest.args:type_name -> google.protobuf.Any
	6, // 2: shepherd.EvaluateLogStatsRequest.args:type_name -> google.protobuf.Any
	2, // 3: shepherd.LogProcessor.StartOptimizer:input_type -> shepherd.StartOptimizerRequest
	0, // 4: shepherd.LogProcessor.ProcessLog:input_type -> shepherd.ProcessLogRequest
	4, // 5: shepherd.LogStatsMessenger.EvaluateLogStats:input_type -> shepherd.EvaluateLogStatsRequest
	3, // 6: shepherd.LogProcessor.StartOptimizer:output_type -> shepherd.StartOptimizerReply
	1, // 7: shepherd.LogProcessor.ProcessLog:output_type -> shepherd.ProcessLogReply
	5, // 8: shepherd.LogStatsMessenger.EvaluateLogStats:output_type -> shepherd.EvaluateLogStatsReply
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_shep_log_processor_shep_log_processor_proto_init() }
func file_shep_log_processor_shep_log_processor_proto_init() {
	if File_shep_log_processor_shep_log_processor_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_shep_log_processor_shep_log_processor_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProcessLogRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shep_log_processor_shep_log_processor_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProcessLogReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shep_log_processor_shep_log_processor_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartOptimizerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shep_log_processor_shep_log_processor_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartOptimizerReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shep_log_processor_shep_log_processor_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EvaluateLogStatsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shep_log_processor_shep_log_processor_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EvaluateLogStatsReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_shep_log_processor_shep_log_processor_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_shep_log_processor_shep_log_processor_proto_goTypes,
		DependencyIndexes: file_shep_log_processor_shep_log_processor_proto_depIdxs,
		MessageInfos:      file_shep_log_processor_shep_log_processor_proto_msgTypes,
	}.Build()
	File_shep_log_processor_shep_log_processor_proto = out.File
	file_shep_log_processor_shep_log_processor_proto_rawDesc = nil
	file_shep_log_processor_shep_log_processor_proto_goTypes = nil
	file_shep_log_processor_shep_log_processor_proto_depIdxs = nil
}
