// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.12.4
// source: shep_log_processor/shep_log_processor.proto

package shep_remote_muster

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LogProcessor_StartOptimizer_FullMethodName = "/shepherd.LogProcessor/StartOptimizer"
	LogProcessor_ProcessLog_FullMethodName     = "/shepherd.LogProcessor/ProcessLog"
)

// LogProcessorClient is the client API for LogProcessor service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LogProcessorClient interface {
	StartOptimizer(ctx context.Context, in *StartOptimizerRequest, opts ...grpc.CallOption) (*StartOptimizerReply, error)
	// rpc StopOptimizer (StopOptimizerRequest) returns (StopOptimizerReply);
	ProcessLog(ctx context.Context, in *ProcessLogRequest, opts ...grpc.CallOption) (*ProcessLogReply, error)
}

type logProcessorClient struct {
	cc grpc.ClientConnInterface
}

func NewLogProcessorClient(cc grpc.ClientConnInterface) LogProcessorClient {
	return &logProcessorClient{cc}
}

func (c *logProcessorClient) StartOptimizer(ctx context.Context, in *StartOptimizerRequest, opts ...grpc.CallOption) (*StartOptimizerReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartOptimizerReply)
	err := c.cc.Invoke(ctx, LogProcessor_StartOptimizer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logProcessorClient) ProcessLog(ctx context.Context, in *ProcessLogRequest, opts ...grpc.CallOption) (*ProcessLogReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProcessLogReply)
	err := c.cc.Invoke(ctx, LogProcessor_ProcessLog_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LogProcessorServer is the server API for LogProcessor service.
// All implementations must embed UnimplementedLogProcessorServer
// for forward compatibility.
type LogProcessorServer interface {
	StartOptimizer(context.Context, *StartOptimizerRequest) (*StartOptimizerReply, error)
	// rpc StopOptimizer (StopOptimizerRequest) returns (StopOptimizerReply);
	ProcessLog(context.Context, *ProcessLogRequest) (*ProcessLogReply, error)
	mustEmbedUnimplementedLogProcessorServer()
}

// UnimplementedLogProcessorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLogProcessorServer struct{}

func (UnimplementedLogProcessorServer) StartOptimizer(context.Context, *StartOptimizerRequest) (*StartOptimizerReply, error) {
	return nil, status.Error(codes.Unimplemented, "method StartOptimizer not implemented")
}
func (UnimplementedLogProcessorServer) ProcessLog(context.Context, *ProcessLogRequest) (*ProcessLogReply, error) {
	return nil, status.Error(codes.Unimplemented, "method ProcessLog not implemented")
}
func (UnimplementedLogProcessorServer) mustEmbedUnimplementedLogProcessorServer() {}
func (UnimplementedLogProcessorServer) testEmbeddedByValue()                      {}

// UnsafeLogProcessorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LogProcessorServer will
// result in compilation errors.
type UnsafeLogProcessorServer interface {
	mustEmbedUnimplementedLogProcessorServer()
}

func RegisterLogProcessorServer(s grpc.ServiceRegistrar, srv LogProcessorServer) {
	// If the following call panics, it indicates UnimplementedLogProcessorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LogProcessor_ServiceDesc, srv)
}

func _LogProcessor_StartOptimizer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartOptimizerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogProcessorServer).StartOptimizer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LogProcessor_StartOptimizer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogProcessorServer).StartOptimizer(ctx, req.(*StartOptimizerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LogProcessor_ProcessLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProcessLogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogProcessorServer).ProcessLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LogProcessor_ProcessLog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogProcessorServer).ProcessLog(ctx, req.(*ProcessLogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LogProcessor_ServiceDesc is the grpc.ServiceDesc for LogProcessor service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LogProcessor_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "shepherd.LogProcessor",
	HandlerType: (*LogProcessorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartOptimizer",
			Handler:    _LogProcessor_StartOptimizer_Handler,
		},
		{
			MethodName: "ProcessLog",
			Handler:    _LogProcessor_ProcessLog_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "shep_log_processor/shep_log_processor.proto",
}

const (
	LogStatsMessenger_EvaluateLogStats_FullMethodName = "/shepherd.LogStatsMessenger/EvaluateLogStats"
)

// LogStatsMessengerClient is the client API for LogStatsMessenger service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LogStatsMessengerClient interface {
	EvaluateLogStats(ctx context.Context, in *EvaluateLogStatsRequest, opts ...grpc.CallOption) (*EvaluateLogStatsReply, error)
}

type logStatsMessengerClient struct {
	cc grpc.ClientConnInterface
}

func NewLogStatsMessengerClient(cc grpc.ClientConnInterface) LogStatsMessengerClient {
	return &logStatsMessengerClient{cc}
}

func (c *logStatsMessengerClient) EvaluateLogStats(ctx context.Context, in *EvaluateLogStatsRequest, opts ...grpc.CallOption) (*EvaluateLogStatsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EvaluateLogStatsReply)
	err := c.cc.Invoke(ctx, LogStatsMessenger_EvaluateLogStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LogStatsMessengerServer is the server API for LogStatsMessenger service.
// All implementations must embed UnimplementedLogStatsMessengerServer
// for forward compatibility.
type LogStatsMessengerServer interface {
	EvaluateLogStats(context.Context, *EvaluateLogStatsRequest) (*EvaluateLogStatsReply, error)
	mustEmbedUnimplementedLogStatsMessengerServer()
}

// UnimplementedLogStatsMessengerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLogStatsMessengerServer struct{}

func (UnimplementedLogStatsMessengerServer) EvaluateLogStats(context.Context, *EvaluateLogStatsRequest) (*EvaluateLogStatsReply, error) {
	return nil, status.Error(codes.Unimplemented, "method EvaluateLogStats not implemented")
}
func (UnimplementedLogStatsMessengerServer) mustEmbedUnimplementedLogStatsMessengerServer() {}
func (UnimplementedLogStatsMessengerServer) testEmbeddedByValue()                           {}

// UnsafeLogStatsMessengerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LogStatsMessengerServer will
// result in compilation errors.
type UnsafeLogStatsMessengerServer interface {
	mustEmbedUnimplementedLogStatsMessengerServer()
}

func RegisterLogStatsMessengerServer(s grpc.ServiceRegistrar, srv LogStatsMessengerServer) {
	// If the following call panics, it indicates UnimplementedLogStatsMessengerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LogStatsMessenger_ServiceDesc, srv)
}

func _LogStatsMessenger_EvaluateLogStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EvaluateLogStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogStatsMessengerServer).EvaluateLogStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LogStatsMessenger_EvaluateLogStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogStatsMessengerServer).EvaluateLogStats(ctx, req.(*EvaluateLogStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LogStatsMessenger_ServiceDesc is the grpc.ServiceDesc for LogStatsMessenger service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LogStatsMessenger_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "shepherd.LogStatsMessenger",
	HandlerType: (*LogStatsMessengerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "EvaluateLogStats",
			Handler:    _LogStatsMessenger_EvaluateLogStats_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "shep_log_processor/shep_log_processor.proto",
}
