# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from shep_log_processor import shep_log_processor_pb2 as shep__log__processor_dot_shep__log__processor__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in shep_log_processor/shep_log_processor_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class LogProcessorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StartOptimizer = channel.unary_unary(
                '/shepherd.LogProcessor/StartOptimizer',
                request_serializer=shep__log__processor_dot_shep__log__processor__pb2.StartOptimizerRequest.SerializeToString,
                response_deserializer=shep__log__processor_dot_shep__log__processor__pb2.StartOptimizerReply.FromString,
                _registered_method=True)
        self.ProcessLog = channel.unary_unary(
                '/shepherd.LogProcessor/ProcessLog',
                request_serializer=shep__log__processor_dot_shep__log__processor__pb2.ProcessLogRequest.SerializeToString,
                response_deserializer=shep__log__processor_dot_shep__log__processor__pb2.ProcessLogReply.FromString,
                _registered_method=True)


class LogProcessorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StartOptimizer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ProcessLog(self, request, context):
        """	rpc StopOptimizer (StopOptimizerRequest) returns (StopOptimizerReply);
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LogProcessorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StartOptimizer': grpc.unary_unary_rpc_method_handler(
                    servicer.StartOptimizer,
                    request_deserializer=shep__log__processor_dot_shep__log__processor__pb2.StartOptimizerRequest.FromString,
                    response_serializer=shep__log__processor_dot_shep__log__processor__pb2.StartOptimizerReply.SerializeToString,
            ),
            'ProcessLog': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessLog,
                    request_deserializer=shep__log__processor_dot_shep__log__processor__pb2.ProcessLogRequest.FromString,
                    response_serializer=shep__log__processor_dot_shep__log__processor__pb2.ProcessLogReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'shepherd.LogProcessor', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('shepherd.LogProcessor', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LogProcessor(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StartOptimizer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/shepherd.LogProcessor/StartOptimizer',
            shep__log__processor_dot_shep__log__processor__pb2.StartOptimizerRequest.SerializeToString,
            shep__log__processor_dot_shep__log__processor__pb2.StartOptimizerReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ProcessLog(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/shepherd.LogProcessor/ProcessLog',
            shep__log__processor_dot_shep__log__processor__pb2.ProcessLogRequest.SerializeToString,
            shep__log__processor_dot_shep__log__processor__pb2.ProcessLogReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class LogStatsMessengerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.EvaluateLogStats = channel.unary_unary(
                '/shepherd.LogStatsMessenger/EvaluateLogStats',
                request_serializer=shep__log__processor_dot_shep__log__processor__pb2.EvaluateLogStatsRequest.SerializeToString,
                response_deserializer=shep__log__processor_dot_shep__log__processor__pb2.EvaluateLogStatsReply.FromString,
                _registered_method=True)


class LogStatsMessengerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def EvaluateLogStats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LogStatsMessengerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'EvaluateLogStats': grpc.unary_unary_rpc_method_handler(
                    servicer.EvaluateLogStats,
                    request_deserializer=shep__log__processor_dot_shep__log__processor__pb2.EvaluateLogStatsRequest.FromString,
                    response_serializer=shep__log__processor_dot_shep__log__processor__pb2.EvaluateLogStatsReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'shepherd.LogStatsMessenger', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('shepherd.LogStatsMessenger', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LogStatsMessenger(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def EvaluateLogStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/shepherd.LogStatsMessenger/EvaluateLogStats',
            shep__log__processor_dot_shep__log__processor__pb2.EvaluateLogStatsRequest.SerializeToString,
            shep__log__processor_dot_shep__log__processor__pb2.EvaluateLogStatsReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
